name: Test
on:
  push:
    # Avoid duplicate builds on PRs.
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        version: [latest, lts/*, lts/-1, lts/-2]
        os: [windows-latest, macos-latest, ubuntu-latest]
    name: Node ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
